### PR TITLE
Avoid empty Enum fields in expired weather alerts

### PR DESCRIPTION
**Pull request by McBits**
Check if string is null/empty before attempting to parse as enum. Set to
(EnumType).Unknown manually if needed. Only fixed enough for the
specific fields that were failing at this time.

### CODE REVIEW

**Comment by vgrigoriu** [comment]
Looks good.

What's the source of the CAP alert with missing severity, certainty and urgency? In the protocol they appear as required.

**Comment by McBits** [comment]
I've been fetching random items from the list at http://alerts.weather.gov/cap/us.atom and occasionally they would throw an exception due to the empty fields. One example at the moment is:

http://alerts.weather.gov/cap/wwacapget.php?x=MS1253A8E3B1C0.SevereWeatherStatement.1253A8E3C354MS.MOBSVSMOB.e3f91f7ee21c093b9f77b6573d666b47

**Comment by vgrigoriu** [comment]
I pushed the new version to nuget: https://www.nuget.org/packages/cap-net/1.0.2

**Comment by McBits** [comment]
Thanks! I've been meaning to try this newfangled GitHub thing for a while. Now I see why everyone likes it. :+1:

**Comment by vgrigoriu** [comment]
Thank you for the pull request!

**Pull request merged**
